apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  selector:
    matchLabels:
      app: website
  replicas: 3
  strategy:
    type: RollingUpdate
     
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx-website
        image: routeg/website:15
        ports:
          - containerPort: 80

        
        